#!/bin/bash
trap "echo -ne '\nstopping container...' && docker stop refinery-embedder > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

HOST_IP=$(docker network inspect bridge --format='{{json .IPAM.Config}}' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | tail -1)

echo -ne 'stopping old container...'
docker stop refinery-embedder > /dev/null 2>&1
echo -ne '\t [done]\n'

echo -ne 'building container...'
docker build -t refinery-embedder-dev -f dev.Dockerfile .
echo -ne '\t\t [done]\n'

echo -ne 'starting...'
docker run -d --rm \
--name refinery-embedder \
-p 7058:80 \
-e S3_ENDPOINT_LOCAL=object-storage:9000 \
-e S3_ACCESS_KEY=onetask \
-e S3_SECRET_KEY=r6ywtR33!DMlaL*SUUdy \
-e POSTGRES=postgresql://postgres:onetask@graphql-postgres:5432 \
-e DOC_OCK=http://refinery-doc-ock:80 \
-e WS_NOTIFY_ENDPOINT="http://refinery-websocket:8080" \
-e NEURAL_SEARCH=http://refinery-neural-search:80 \
--mount type=bind,source="$(pwd)"/,target=/app \
-v /var/run/docker.sock:/var/run/docker.sock \
--network dev-setup_default \
refinery-embedder-dev > /dev/null 2>&1
echo -ne '\t\t\t [done]\n'

docker logs -f refinery-embedder
